import "./index.scss";

export default {
  title: "Components/Content",
};

export const Base = () => `
<main class="content">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc non orci luctus, consectetur tellus vitae, luctus enim. Phasellus placerat convallis felis, eget aliquam felis vulputate quis. Duis tincidunt ante et nisl elementum, eget gravida lorem mollis. In ac augue ac sapien sagittis interdum. Suspendisse blandit ipsum varius urna aliquet mattis. Nam et mollis augue. Sed vitae dapibus quam. Phasellus eros metus, mollis vel mollis ac, maximus ac magna.</p>
  <p>Etiam ligula odio, tristique suscipit ultricies facilisis, facilisis in urna. Proin sed lacinia lacus, sit amet mattis purus. Vivamus vehicula, massa et blandit elementum, arcu ex facilisis diam, sit amet faucibus purus lacus eget nisl. Vivamus vel orci pellentesque, cursus eros eu, sagittis nibh. Phasellus at dignissim sem. Donec tincidunt nisi ut ligula tempor auctor. Proin ut augue ut quam lobortis aliquet ut a tortor. Nullam faucibus dolor vel mauris scelerisque hendrerit. Quisque rhoncus tellus sed dui tincidunt laoreet vitae quis mi. Ut ac dui sed lorem ullamcorper feugiat at et nulla. Donec facilisis justo a tincidunt facilisis. Cras ac consectetur sapien. Integer orci mauris, commodo tempus velit et, pretium viverra ipsum.</p>
  <p>Nullam porttitor facilisis dapibus. Pellentesque vitae eros at felis congue vehicula. Sed diam urna, tempus ac commodo ac, convallis ut felis. Nulla lectus urna, fermentum quis est at, tempus congue augue. Nulla eu fringilla augue. Aliquam sit amet rhoncus enim. Phasellus mollis sit amet turpis nec bibendum. Integer sem sem, imperdiet sed augue sit amet, aliquet gravida metus. Aenean sit amet ligula at orci vehicula mollis. Etiam nec luctus est. Nullam accumsan hendrerit nibh, et facilisis urna rhoncus non. Pellentesque eu molestie tortor.</p>
  <p>Nam facilisis id quam porttitor viverra. Pellentesque vel interdum nibh. Suspendisse eget nulla facilisis ipsum pellentesque elementum. Curabitur pharetra volutpat tortor vitae eleifend. Maecenas ac sapien a sapien gravida commodo. Aliquam volutpat sapien quis tortor sagittis fringilla. Fusce quis luctus est, quis sollicitudin dui. Donec non libero urna. Duis pellentesque quam ac dui maximus posuere ac id ante. In augue eros, imperdiet et semper sed, fringilla vitae arcu. In eget rhoncus enim. Mauris nisl neque, malesuada quis pellentesque eu, convallis et diam. Donec luctus eleifend blandit. Praesent in volutpat purus. Duis elementum at sapien in feugiat. Morbi id elit ac mauris varius vestibulum in viverra lorem.</p>
  <p>Aenean neque odio, efficitur aliquet odio varius, commodo feugiat massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pharetra dui at hendrerit sodales. Fusce varius urna vel mi finibus, a ultrices nisl egestas. Sed at tincidunt eros. Nam vestibulum ante vitae nibh vestibulum mattis. Aenean tincidunt metus vitae ligula cursus, at molestie mauris dictum. Aenean volutpat porta tempus. Maecenas dictum accumsan justo, at euismod metus facilisis vel. Quisque facilisis dignissim nisl, vitae feugiat elit laoreet non. Ut at sapien vitae dui sagittis porttitor. Ut dapibus cursus ante vel tincidunt.</p>
</main>
`;
